### ISSUE TITLE
Dungeons: Enemy information in data logs

### ISSUE THREAD

**Issue by QuatZo** [swarfarm/swarfarm#166] opened 2020-11-06 14:16 UTC
As mentioned by @PeteAndersen in Discord Swarfarm Dev server, *dungeon enemy information is already scrapped and stored, but not displayed anywhere*.

So I've made an example implementation, but there are some things I would like to discuss:
* **Crystal names are not in english**: i.e. **l가드_파랑(중)** (which translates to *[according to Google Translate]* Guard Blue (Medium); is it possible to permanently rename them or every game files update it'll be overwritten (since it uses Monster model)?
* **No B12 data**: I'm pretty sure it's because repo has old *bestiary_data.json* and live site has B11/B12 Enemies, I would like some confirmation
* **No SB/PB dungeons**: As mentioned above
* **No Dimension Hole data**: I see no parser for this; IIRC it's available in run response
* **Rifts/Raids no data**: I see no parser for this; IIRC it's available in run response
* **UI**: [That's my proposition how it would look like](https://user-images.githubusercontent.com/48104274/98374114-7fdb3400-2040-11eb-9436-1c83541b0600.png); since every monster has its own icon, it shouldn't be a problem to add it.

**Edit**
There is also an issue with images, since [crystals have Fei image](https://user-images.githubusercontent.com/48104274/98378656-9b493d80-2046-11eb-9c8c-a62992136cd5.png)

**Comment by PeteAndersen** [comment] 2020-11-06 17:03
**Crystal names**: There's a system in bestiary.parse.monsters where you can run specific functions after parsing to fix issues that are known from the game data (see [here](https://github.com/PeteAndersen/swarfarm/blob/c9537b249e3b2867f6afbf6ed6edd141879a55db/bestiary/parse/monsters.py#L185)). This would work both to provide translated names and remove/correct the Fei image. The problem is we need a concrete list of all the crystal tower monster IDs. 

**B12/SB/PB**: Yes this data is available on the live site. I'll update bestiary_data.json with this information.

**DimHole/Rift/Raid**: Correct this info isn't parsed out. Open to adding it. 

**UI**: I like it, but keep in mind mobile/narrow screen use case. `Boss` column could maybe be merged into Monster column by prefixing the name with an icon or `Boss` [bootstrap badge](https://getbootstrap.com/docs/3.3/components/#badges)

**Comment by QuatZo** [comment] 2020-11-06 19:11
> **Crystal names**: There's a system in bestiary.parse.monsters where you can run specific functions after parsing to fix issues that are known from the game data (see [here](https://github.com/PeteAndersen/swarfarm/blob/c9537b249e3b2867f6afbf6ed6edd141879a55db/bestiary/parse/monsters.py#L185)). This would work both to provide translated names and remove/correct the Fei image. The problem is we need a concrete list of all the crystal tower monster IDs.

All Caiross crystals with errors, saving here for the future.
**Edit**: There's a lot more instances for these crystals, already implemented in one commit
```
>>> Hall of Magic
Consists of crystals from other dungeons

>>> Hall of Water
210106 - small water crystal
210606 - medium water crystal

>>> Hall of Fire
210206 - small fire crystal
210706 - medium fire crystal

>>> Hall of Wind
210306 - small wind crystal
210806 - medium wind crystal

>>> Hall of Light
210406 - small light crystal
210906 - medium light crystal

>>> Hall of Dark
210506 - small dark crystal
211006 - medium dark crystal

>>> Giant's Keep
100816 - left tower
101116 - right tower

>>> Dragon's Lair
101426 - left tower
101526 - right tower

>>> Steel Fortress
200113 - medium wind eye
200103 - small wind eye
112023 - left mid & boss eye
112033 - right mid & boss eye
62303  - light mid boss

>>> Punisher's Crypt
200214 - medium light eye
200204 - small light eye
112124 - left mid & boss eye
112134 - right mid & boss eye
62504  - light mid boss
```

**Comment by QuatZo** [comment] 2020-11-07 15:27
Forgot to mention this issue in [previous commit](https://github.com/QuatZo/swarfarm/commit/0a8d565d065d74b2f6dae1ec6353bfe182155c49). There was **A LOT** more crystals to fix from game data.

I've added Dimension Hole wave parser, together with new active log command (*BattleDimensionHoleDungeonStart*). As for now it looks like this:
* [Dim Hole boss with runes](https://user-images.githubusercontent.com/48104274/98445009-84bde780-2115-11eb-9fd1-da47c01f8b8c.png)
* [2A Dim Hole](https://user-images.githubusercontent.com/48104274/98445027-a8812d80-2115-11eb-87e2-db4140ff163e.png)

I'm looking for a way to make it mobile-friendly. Also, Raids and Rift of Worlds are kind of tricky, since these are not exactly dungeons with waves. Not sure if it's worth adding

**Comment by QuatZo** [comment] 2020-11-08 00:38
I'm actually quite confused by the [values in table](https://user-images.githubusercontent.com/48104274/98454259-dd67a180-2162-11eb-9aec-88f950230bee.png) (look at critical rate and accuracy).

It kind of looks like it should be substituted from base values in database (15 crit rate, 30 accuracy for boss). Does anyone know something about this?

**Closed as completed** 2020-11-10 05:20 UTC
